# Generated by Django 4.2.3 on 2025-01-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_created_at_stock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('Necklace Set', 'NECKLACE_SET'), ('Pendant Set', 'PENDANT_SET'), ('Mangalsutra', 'MANGALSUTRA'), ('Finger Ring', 'FINGER_RING'), ('Nose Pin', 'NOSE_PIN'), ('Neckwear', 'NECKWEAR'), ('Bracelet', 'BRACELET'), ('Earring', 'EARRING'), ('Pendant', 'PENDANT'), ('Bangle', 'BANGLE'), ('Chain', 'CHAIN'), ('Coin', 'COIN'), ('Other', 'OTHER')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='material',
            field=models.CharField(choices=[('Gold', 'GOLD'), ('Silver', 'SILVER'), ('Diamond', 'DIAMOND'), ('Platinum', 'PLATINUM'), ('Ruby', 'RUBY'), ('Other', 'OTHER')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
