# Generated by Django 4.2.3 on 2025-08-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stock_purchase_price_alter_stock_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='karat',
            field=models.CharField(choices=[('6', '6'), ('8', '8'), ('9', '9'), ('10', '10'), ('12', '12'), ('14', '14'), ('15', '15'), ('18', '18'), ('20', '20'), ('21', '21'), ('22', '22'), ('24', '24')], default='24', max_length=5),
        ),
    ]
