# Generated by Django 5.2.5 on 2025-08-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stock_karat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_deleted',
        ),
    ]
