# Generated by Django 4.2.3 on 2024-12-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='email',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='phone',
        ),
        migrations.AddField(
            model_name='salebill',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salebills', to='transactions.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
