# Generated by Django 4.2.3 on 2024-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_salebill_address_remove_salebill_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='due_amount',
            field=models.IntegerField(default=0),
        ),
    ]
