# Generated by Django 4.2.3 on 2025-07-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_salebill_payment_amount_salebill_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebill',
            name='discount_type',
            field=models.CharField(blank=True, choices=[(None, 'NO'), ('Fixed', 'FIXED'), ('Percentage', 'PERCENTAGE')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salebill',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
