# Generated by Django 4.2.3 on 2025-07-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_salebill_discount_type_salebill_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('Fixed', 'FIXED'), ('Percentage', 'PERCENTAGE')], default='', max_length=10, null=True),
        ),
    ]
