# Generated by Django 4.2.3 on 2025-07-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_salebill_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'CASH'), ('Card', 'CARD'), ('UPI', 'UPI'), ('Other', 'OTHER')], default='Cash', max_length=50, null=True),
        ),
    ]
