# Generated by Django 4.2.3 on 2025-08-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_salebill_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebill',
            name='discount_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
