# Generated by Django 4.2.3 on 2025-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_salebill_discount_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebilldetails',
            name='total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salebilldetails',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
