# Generated by Django 4.2.3 on 2025-08-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_salebilldetails_total_after_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebilldetails',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
