# Generated by Django 4.2.3 on 2025-08-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_remove_purchasebilldetails_cess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebilldetails',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
