# Generated by Django 4.2.3 on 2025-08-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_salebilldetails_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
