# Generated by Django 4.2.3 on 2025-08-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_saleitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='discount_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('Fixed', 'FIXED'), ('Percentage', 'PERCENTAGE')], default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'CASH'), ('Card', 'CARD'), ('UPI', 'UPI'), ('Other', 'OTHER')], default='Cash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
