# Generated by Django 4.2.3 on 2025-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_purchasebill_discount_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='due_amount',
        ),
    ]
