# Generated by Django 4.2.3 on 2025-08-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_remove_customer_deposit_remove_customer_due_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='labour_making_charge_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='labour_making_charge_type',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('Fixed', 'FIXED'), ('Per Gram', 'PERGRAM')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='labour_making_charge_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='total_labour_making_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salebill',
            name='labour_making_charge_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salebill',
            name='labour_making_charge_type',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('Fixed', 'FIXED'), ('Per Gram', 'PERGRAM')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salebill',
            name='labour_making_charge_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salebilldetails',
            name='total_labour_making_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salebilldetails',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
