# Generated by Django 4.2.3 on 2025-08-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_purchasebill_labour_making_charge_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='stock_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='stock_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
