# Generated by Django 5.2.5 on 2025-08-12 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_customer_address_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
