# Generated by Django 5.2.5 on 2025-08-12 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_customer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
