# Generated by Django 5.2.5 on 2025-08-12 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_supplier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
