# Generated by Django 5.2.5 on 2025-08-12 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_purchaseitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
