# Generated by Django 5.2.5 on 2025-08-13 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_alter_purchasebill_time_alter_salebill_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
