# Generated by Django 5.2.5 on 2025-08-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_alter_purchasebill_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebill',
            name='old_stuff_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salebill',
            name='old_stuff_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
