# Generated by Django 5.2.5 on 2025-08-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_salebill_old_stuff_note_salebill_old_stuff_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='old_stuff_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='old_stuff_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
