# Generated by Django 4.2.3 on 2025-07-29 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giravee',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giravee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='giravee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='giravee',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='giravee',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='GiraveeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('giravee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='giravee.giravee')),
            ],
        ),
    ]
