# Generated by Django 4.2.3 on 2025-07-29 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0003_giravee_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giravee',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='giraveetransaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
