# Generated by Django 4.2.3 on 2025-07-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0004_alter_giravee_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giravee',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
