# Generated by Django 4.2.3 on 2025-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0005_giravee_interest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='giravee',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
