# Generated by Django 4.2.3 on 2025-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0006_giravee_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='giravee',
            name='due_amount_without_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
