# Generated by Django 4.2.3 on 2025-08-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0007_giravee_due_amount_without_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='giravee',
            name='locker_number',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten')], default='1', max_length=2),
        ),
    ]
