# Generated by Django 5.2.5 on 2025-08-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0008_giravee_locker_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giravee',
            name='is_deleted',
        ),
    ]
