# Generated by Django 5.2.5 on 2025-08-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0009_remove_giravee_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='giravee',
            name='interest_type',
            field=models.CharField(choices=[('Simple', 'SIMPLE'), ('Compound', 'COMPOUND')], default='Compound', max_length=10),
        ),
    ]
