# Generated by Django 5.2.5 on 2025-08-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0010_giravee_interest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='giravee',
            name='days_since_start',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
