# Generated by Django 5.2.5 on 2025-08-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giravee', '0011_giravee_days_since_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giravee',
            name='due_amount_without_interest',
        ),
    ]
